# Statistics Guided Exercise

For using statistics with Python, we will be looking at the Pandas library.  Pandas itself is build on top of another library, NumPy, and both have their own data structures.  In this exercise, we will go over these data structures, and introduce you to Bokeh, which is a visualisation library you will be using in this exercise and the next for graphs and charts.

## Pandas

Pandas is a Python library for data analysis in Python.  It providies some useful functions and data structures for the collection and analysis of data.  In particular, we will be making use of the **`DataFrame`** and **`Series`** classes.  

A `DataFrame` object represents data in a series of rows (individual observations of data) and columns (features or variables) within those data.  Each of those rows and columns can be extracted, and they then become a `Series`.  We will work through an example to illustrate these concepts.

### Importing Data

There are convenience functions to import data, such as [**`read_json`**](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_json.html) and [**`read_csv`**](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) which, as their names suggest, will import data which is already in a particular format.  For this example, we will import data from the MongoDB database we used in the exercise last week.

For this example, we will import the first 1000 documents (*MongoDB stores data records as BSON documents. BSON is a binary representation of JSON documents, though it contains more data types than JSON*), in the UK collection into a Pandas `DataFrame`.  Run the cell below

In [1]:
# Convention is to import numpy and pandas with abbreviated names
# This means that instead of using pandas.read_csv, you would use pd.read_csv
import numpy as np
import pandas as pd

from bokeh.io import output_notebook, show
from bokeh.charts import *

# Import PyMongo, so that we can query some data
# 'mongodb://cpduser:M13pV5woDW@mongodb/health_data' is the location of the data we will be using

from pymongo import MongoClient
client = MongoClient('mongodb://cpduser:M13pV5woDW@mongodb/health_data')
db = client.health_data

cursor = db.uk.find({}).limit(1000)

# Unfortunately, Pandas does not support PyMongo objects for import, so we need to cast it to a list
listy = list(cursor)

# Create a Pandas DataFrame with the list object as a parameter
first_1000 = pd.DataFrame(listy)

Now we have our imported data in a **`DataFrame`** object.  Like any other Python object, it has a collection of attributes and methods which we can use.  We will go over some here, but see [the documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) for a full list.  We'll start by seeing what the data looks like by calling the `head()` function on the data:

In [2]:
# Filtering the data in the DataFrame to only return rows where RatingValue < 3
first_1000[first_1000['RatingValue'] < 3]

AddressLine1              AddressLine2 AddressLine3  \
3                                 NaN       30-34 Holmrook Road      Preston   
19                                NaN            53A Fylde Road      Preston   
64                                NaN         130 Church Street      Preston   
85                                NaN     158-162 New Hall Lane      Preston   
108                               NaN     161-163 St Pauls Road      Preston   
120                               NaN          21 Harewood Road      Preston   
127                               NaN             69 Fylde Road      Preston   
180                               NaN          198c Miller Road      Preston   
189                               NaN        91 Fishergate Hill      Preston   
206                               NaN         169 St Pauls Road      Preston   
230                               NaN        214 Ribbleton Lane      Preston   
265                               NaN             57 Marsh Lane      Preston   
272                               NaN          69 Meadow Street      Preston   
273                               NaN        434 Blackpool Road      Preston   
276                               NaN        16b Adelphi Street      Preston   
292                               NaN         49 Blackpool Road      Preston   
327                               NaN           33-35 Moor Lane      Preston   
350                               NaN        393 Blackpool Road      Preston   
398                               NaN          25 New Hall Lane      Preston   
426                               NaN         198 New Hall Lane      Preston   
432                               NaN         194 Fletcher Road      Preston   
459                               NaN           29 Market Place      Preston   
469                               NaN     230-232 New Hall Lane      Preston   
474                               NaN            68 Watery Lane      Preston   
518                               NaN         284 New Hall Lane      Preston   
561                  1b Aqueduct Mill       222 Aqueduct Street      Preston   
575                               NaN        954 Blackpool Road      Preston   
632                               NaN        241 Ribbleton Lane      Preston   
648                               NaN       50 Greenbank Street      Preston   
654                               NaN           154 Miller Road      Preston   
663                 Fishergate Centre                Fishergate      Preston   
665                               NaN       60 Plungington Road      Preston   
687                               NaN          27 Church Street      Preston   
700                               NaN       138 Manchester Road      Preston   
704                               NaN         169 New Hall Lane      Preston   
719                               NaN             140 Friargate      Preston   
752                               NaN      119 Ribbleton Avenue      Preston   
787                               NaN                Eaves Lane      Preston   
821                               NaN    42-46 Holme Slack Lane      Preston   
827   Unit B1b Deepdale Shopping Park            Blackpool Road      Preston   
828                               NaN              281 Tag Lane      Preston   
829                               NaN  15-17 Corporation Street      Preston   
856                               NaN         454 New Hall Lane      Preston   
863                               NaN      4-6 Ribbleton Avenue      Preston   
868  Farringdon Park Community Centre      18-24 Thirlmere Road      Preston   
871                               NaN         7 Manchester Road      Preston   
896                               NaN         172 Deepdale Road      Preston   
912                               NaN              18 East View      Preston   
925                               NaN     323-325 Garstang Road      Preston   
936                      

In [3]:
# We can also create a DataFrame which has only some columns
three_columns = first_1000[['RatingValue', 'FHRSID', 'PostCode']]

print('DataFrame with COLUMNS only:\n\n', three_columns.head())

# Or some rows
# Print the Dataframe with rows 950 to 960, could be any number of rows
print("\nDataFrame with a selection of ROWS:")
first_1000[950:960]


DataFrame with COLUMNS only:

    RatingValue  FHRSID PostCode
0          3.0   90105  PR1 7BE
1          5.0  479725  PR1 7BY
2          5.0  479676  PR1 3BT
3          2.0  135423  PR1 6SR
4          5.0  759083      NaN

DataFrame with a selection of ROWS:


AddressLine1        AddressLine2 AddressLine3 AddressLine4  \
950          NaN        Sherwood Way      Preston          NaN   
951          NaN        Sherwood Way      Preston          NaN   
952          NaN     14 Avenham Road      Preston          NaN   
953          NaN        3 Fylde Road      Preston          NaN   
954          NaN   171 New Hall Lane      Preston          NaN   
955          NaN  219 Ribbleton Lane      Preston          NaN   
956          NaN                 NaN          NaN          NaN   
957          NaN                 NaN          NaN          NaN   
958          NaN                 NaN          NaN          NaN   
959          NaN      Blackpool Road      Preston          NaN   

                             BusinessName  \
950                        Sherwood Court   
951         Sherwood Lodge Res. Care Home   
952                 Shining Stars Nursery   
953                       Ships & Giggles   
954                             Shop Rite   
955                           Sicilia Uno   
956                   Simply Country & Co   
957                         Simply Delish   
958                            Sion House   
959  Sir Tom Finney Community High School   

                            BusinessType BusinessTypeID  \
950  Hospitals/Childcare/Caring Premises              5   
951  Hospitals/Childcare/Caring Premises              5   
952  Hospitals/Childcare/Caring Premises              5   
953                    Pub/bar/nightclub           7843   
954                    Retailers - other           4613   
955               Takeaway/sandwich shop           7844   
956              Other catering premises           7841   
957              Other catering premises           7841   
958  Hospitals/Childcare/Caring Premises              5   
959            School/college/university           7845   

     ConfidenceInManagement  FHRSID  \
950                     0.0   89945   
951                     0.0   71554   
952                     5.0  113875   
953                     5.0   84750   
954                    10.0  479819   
955                    10.0  479673   
956                     5.0  615337   
957                    10.0  781689   
958                     5.0  448075   
959                     5.0   77773   

                                               Geocode  \
950  {'type': 'Point', 'coordinates': [-2.695381, 5...   
951  {'type': 'Point', 'coordinates': [-2.695381, 5...   
952  {'type': 'Point', 'coordinates': [-2.698297, 5...   
953  {'type': 'Point', 'coordinates': [-2.7099, 53....   
954  {'type': 'Point', 'coordinates': [-2.677047, 5...   
955  {'type': 'Point', 'coordinates': [-2.681433, 5...   
956                                               None   
957                                               None   
958                                               None   
959  {'type': 'Point', 'coordinates': [-2.695976, 5...   

               ...             PostCode  RatingDate     RatingKey RatingValue  \
950            ...              PR2 9GA  2015-02-26  fhrs_5_en-GB         5.0   
951            ...              PR2 9GA  2015-02-26  fhrs_5_en-GB         5.0   
952            ...              PR1 3TH  2016-01-14  fhrs_5_en-GB         5.0   
953            ...              PR1 2XQ  2015-03-06  fhrs_4_en-GB         4.0   
954            ...              PR1 5XA  2015-04-14  fhrs_2_en-GB         2.0   
955            ...              PR1 5DY  2015-03-26  fhrs_3_en-GB         3.0   
956            ...                  NaN  2015-09-25  fhrs_5_en-GB         5.0   
957            ...                  NaN  2015-06-22  fhrs_4_en-GB         4.0   
958            ...                  NaN  2015-09-08  fhrs_5_en-GB         5.0   
959            ...              PR1 6AU  2014-11-27  fhrs_5_en-GB         5.0   

         Region RightToReply SchemeType  \
950  north_west          NaN       FHRS   
951  north_west          NaN       FHRS   
952  north_west          NaN       FHRS  

Using the existing `first_1000` DataFrame, try and create a dataset which outputs the columns FHRSID, PostCode, LocalAuthorityName, with any establishment where `RatingValue < 3`


In [4]:
# YOUR CODE HERE
three_columns = first_1000[first_1000['RatingValue'] < 3][['FHRSID', 'PostCode', 'LocalAuthorityName']]
print('DataFrame with COLUMNS only:\n\n', three_columns)

DataFrame with COLUMNS only:

      FHRSID PostCode LocalAuthorityName
3    135423  PR1 6SR            Preston
19   479641  PR1 2XQ            Preston
64   335295  PR1 3BT            Preston
85   448032  PR1 4DX            Preston
108  454884  PR1 1PX            Preston
120   51647  PR1 6XH            Preston
127  448082  PR1 2XQ            Preston
180  369063  PR2 6NH            Preston
189   69893  PR1 8JD            Preston
206   86973  PR1 1PX            Preston
230  637915  PR1 5LD            Preston
265  335352  PR1 8RQ            Preston
272  121600  PR1 1TS            Preston
273  133196  PR2 2DX            Preston
276  335380  PR1 7BE            Preston
292  335301  PR2 6BU            Preston
327  479591  PR1 7AT            Preston
350  201373  PR2 2DU            Preston
398  629593  PR1 5NU            Preston
426  479519  PR1 4SS            Preston
432  115804  PR1 5HH            Preston
459  479764  PR1 2AR            Preston
469  479921  PR1 4ST            Preston
474  7682

A `DataFrame` is an object in the `Pandas` library, but in addition we have the `Series` object, a collection of which makes up the `DataFrame`.  

Many of the operations we can perform on a `Series` can also be performed on a `DataFrame`.  It is a `Series` object which we will be using this week.

It is possible to perform an operation on each element in the `Series`, as well as call functions which require all of these such as `mean()`.

In [5]:
print(first_1000['RatingValue'].head(), '\n')
print(first_1000['RatingValue'].head() * 100, '\n')
print(first_1000['RatingValue'].head() * 23 > 100)

0    3.0
1    5.0
2    5.0
3    2.0
4    5.0
Name: RatingValue, dtype: float64 

0    300.0
1    500.0
2    500.0
3    200.0
4    500.0
Name: RatingValue, dtype: float64 

0    False
1     True
2     True
3    False
4     True
Name: RatingValue, dtype: bool


As well as being a part of a `DataFrame`, it is possible to create a `Series` from a list type object, for example see the code below:

In [6]:
s = pd.Series([8,6,2,7,9,6])
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0    8
1    6
2    2
3    7
4    9
5    6
dtype: int64


Create a `Series` object `rating_series` which contains the `RatingValue` column from the `first_1000 DataFrame` object.

Then display descriptive statistics from that object (mean, median, mode etc).  You can see the full list of available functions in [the documentation](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html)

In [7]:
# YOUR CODE HERE
rating_series = pd.Series(first_1000['RatingValue'])
mean = rating_series.mean()
median = rating_series.median()
mode = rating_series.mode()

print(mean)
print(median)
print(mode)

4.29613733906
5.0
0    5.0
dtype: float64


## Bokeh Charts
Bokeh uses Pandas data structures as the basis for its charts.  We will now place the data structure we just generated onto various types of charts.

In Bokeh, there is a class **`Plot`** which is the basis for the visualisations we will consider in more detail next week.  A **`Chart`** is a *subclass* of **`Plot`**, which is designed to allow the generation of common charts with the minimum amount of code.

At its simplest, these charts simply accept an object such as a `DataFrame` or `Series`, and will output a chart.  For example, a simple bar chart looks as follows:

In [19]:
# To display the chart in the notebook, we need to run this function, otherwise calling 'show' will not work
output_notebook()
# Create a simple bar chart with made up data
bar_chart = Bar(pd.Series([8,6,2,7,9,3]))

# Display the bar chart
show(bar_chart)

Loading BokehJS ...

There are other charts which you can use such as a Histogram, Line graph, and scatter plot.  View the Bokeh **[user guide for charts](http://bokeh.pydata.org/en/latest/docs/reference/charts.html)** to see the options available to customise the chart created above.  In addition it is possible to customise the display.

# Randomness

A feature which NumPy supports is that of generating random numbers.  This is important, for example, in generating a random sample from a population.  The randomness, however, is not _truly_ random, but rather pseudo-random, i.e., it will generate predictable values based on the initial _seed_ that it accepts.

This feature means that if we know the seed, we can reproduce the results we wish to share provided that we have the same data, which is a desirable property. Though this may sound counter-intuitive it allows others to run our code using the same seed and they will get the same output, the code can then be run using a different seed value.

Consider the scenario where you want to populate an array with random data, you can use the `numpy.random.randint` function as below:

In [9]:
# import numpy.random
import numpy as np
# The numbers generated will include the low value
low = 0
# The numbers generated will not include the high value, but will go up to high - 1
high = 10
np.random.randint(low, high, size=10)

array([0, 2, 6, 7, 8, 7, 6, 5, 1, 9])

Create a loop with 10 iterations, where each iteration prints a randomly generated array of size 10.  Notice how each array has set of different values.

In [10]:
# YOUR CODE HERE
for ri in range(0,10):
    print(np.random.randint(low, high, size=10))

[7 7 8 1 3 1 5 1 0 3]
[5 2 3 2 7 8 3 7 2 6]
[9 5 5 0 8 1 8 5 3 2]
[0 8 1 7 8 2 1 8 3 4]
[7 4 8 8 5 0 6 8 3 6]
[0 5 2 2 8 2 7 8 1 8]
[8 5 2 3 9 7 5 0 3 2]
[6 4 3 6 4 8 7 0 2 5]
[5 1 0 3 1 6 4 5 5 8]
[4 6 3 5 1 0 6 4 1 9]


For many situations, this is desirable.  However, where we want to be able to reproduce, e.g., sample sizes, we want our samples to be reproducible.  To do this, we use the `RandomState` class in NumPy, where we specify our seed, as follows:

In [11]:
# Run this cell several times - observe the outcome
rs = np.random.RandomState(543210)
j = rs.randint(low, high, size=10)
print(j)

[8 4 1 0 7 6 4 6 8 3]


In the cell below, generate the same loop as before, except this time instantiate the `RandomState` object to a value of 123456:

In [12]:
# YOUR CODE HERE
rs = np.random.RandomState(123456)
j = rs.randint(low, high, size=10)
print(j)

[1 2 1 8 0 7 4 8 4 2]


# IQR and Outliers

In the videos, Sergej talked about "outliers" in a dataset.  In this worksheet, we'll give a slightly more detailed definition about what exactly they are, and the effect they can have on data.

An outlier is a value which is atypical of the rest of the dataset.  For example, consider this set of data from [searches on the UK income tax calculator](https://www.incometaxcalculator.org.uk/average-salary-uk.php).  If we draw a distribution of them, we will notice a big difference in the values:

In [13]:
import pandas as pd
import numpy as np
from bokeh.charts import Histogram, output_notebook, show
from bokeh.models import Axis

salaries_list =  [30000,18000,25000,20000,40000,50000,35000,45000,22000,60000,24000,28000,23000,
             16000,100000,21000,26000,15000,32000,19000,17000,70000,27000,55000,18500,80000,
             36000,65000,42000,38000,12000,2481300,75000,33000,19500,43000,48000,120000,14000,
             17500,90000,34000,29000,16500,11000,31000,150000,37000,13000,22500,52000,10000,85000,
             44000,200000,39000,46000,110000,27500,21500,47000,23500,15500,41000,26500,15600,16800,
             20500,14500,130000,250000,24500,28500,72000,140000,32500,8000,53000,95000,25500]


salaries = pd.DataFrame({'Salaries': salaries_list})
print('the max is %f' % (salaries.max()))

from bokeh.plotting import figure, show, output_file
output_notebook()
hist = Histogram(salaries, bins=50)
# Show absolute number on axis rather than E notation:
xaxis = hist.select(dict(type=Axis))[0]
xaxis.formatter.use_scientific = False
show(hist)

the max is 2481300.000000


Loading BokehJS ...

You will notice, the massive outlier on the right, where the person in question earns nearly £2.5 million.  It makes it very difficult to get the chart to display anything useful, and has a significant effect on our data. For example, see the code below which shows the difference in number between the mean and the median:

In [14]:
print('The mean is: %f, and the median is %f' % 
      (salaries.mean(), salaries.median()))

The mean is: 76371.250000, and the median is 31500.000000



Task: Remove the highest value from the dataset and see how this changes the mean and the median.

In [15]:
# YOUR CODE HERE
salaries = salaries.loc[salaries['Salaries'] < 2000000]
print('The mean is: %f, and the median is %f' % (salaries.mean(), salaries.median()))

The mean is: 45929.113924, and the median is 31000.000000


Moving the top value had a considerable effect on the mean value of the dataset, decreasing it by over £30,000, however the result is still quite a bit higher than the median.  So although the £2.5 million figure is obviously an outlier, how can we define an outlier more concretely?  To start, we will consider the interquartile range (IQR):

## IQR

The IQR is calculated as follows:

1. Ordering the data by value

2. Taking the middle value from the _bottom_ half of the data (lower quartile, known as Q1)

3. The median is known as Q2

3. Taking the middle value from the _top_ half of the data (upper quartile, known as Q3)

4. The IQR is then calculated with Q3 - Q1

The Q1 and Q2 values are considered as the 25th and 75th percentiles, since they represent the values 25% and 75% through the ordered data.  Luckily, there are functions within Pandas which allow the calculation of these percentiles, which provide us with the IQR: the [`quantile`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.quantile.html) function on a `DataFrame` which takes a float between 0 and 1 to get the appropriate percentile.  For example, the median could be calculated as follows:

In [16]:
salaries.quantile(0.5)

Salaries    31000.0
Name: 0.5, dtype: float64

Task: Calculate the IQR of the salaries data using Pandas.  Print out the value of the upper and lower quartiles so you can check the answer is correct

In [17]:
# YOUR CODE HERE
upper = float(salaries.quantile(0.75))
lower = float(salaries.quantile(0.25))
iqr = upper - lower
print('Upper quartile:\t%f\nLower quartile:\t%f\nIQR:\t\t%f' % (upper, lower, iqr))

Upper quartile:	51000.000000
Lower quartile:	20250.000000
IQR:		30750.000000


## Outliers

Having introduced the IQR, we can now consider what constitues an outlier.  As a rule of thumb, an outlier can be defined as follows:

- `lower_quartile - (1.5 * IQR)`
- `upper_quartile + (1.5 * IQR)`  

This is highly dependent on the data, and may not be appropriate for all situations, as is the decision of what to do with them.  For the time being, we will simply exclude data which are outside these limits.

To do this, consider the following Pandas code, which excludes outliers from the salaries data.  It uses a more complicated `.loc`, where it filters on two 

In [18]:
# You don't need to write anything here
# Create the dataset again, rather than use the one with the top value taken out
salaries = pd.DataFrame({'Salaries': salaries_list})

salaries = salaries['Salaries'][(salaries['Salaries'] > (float(lower) - (iqr * 1.5)))
                     & (salaries['Salaries'] < (float(upper) + (iqr * 1.5)))]

# salaries = salaries['Salaries'] < lower
# salaries = salaries.loc[salaries['Salaries'] <= lower]
print('The mean is: %f, and the median is %f' % (salaries.mean(), salaries.median()))


The mean is: 34202.816901, and the median is 28000.000000


The purpose of this exercise was to introduce the concept of an outlier, and how much of an effect it can have on data, and to give some practice using Pandas.  There are many different ways that outliers could be defined, and circumstances where they could or should not be excluded.